language: node_js
node_js:
  - "7"
install:
  - npm install
script: 
  - gulp minifyall
branches:
  only:
  - master
env:
  global:
    - secure: "gYPyHCG9z2ghu18IVHfLcL9uJZbQbsYNIjbBD5+H0ZksY4EVvzLvYc/IHfbWWPcUbsUGMfTVS3mbSBy5kQayy/tppOSwSjOupb5YsODXWZQH0YHiShTEvNNoerIRsX119fVjrYpRg6FdbId9edw3QYxbNVTiIoHouEnX6kz81zVKXA+vzcZ1GbugLmVgQZH/U0opVvWaW/hqKl1nyOPH2AlOxf0mvzAFXpmjr+N9actpypsAnj76NxYx+DTghR01Sy3C+bbMFkfH4S6LC61L26BSNCsDBbw4EDetWxtA2m3Fy3a1Gn/mTQZRd+tZflFbIlFyi4FvH2tHu3Ba7HZj8dGim58a9EcWbrg+GN4fisf8D9r70OMKO58VXLR9CXb+IX4CQpsceAqC6isjTvzUU06rpTq+kyiuzdZOYjA0O59/5glVQR2FaLPS4dvHwV6rJ1GbuT65xPYIc/jKd2dEq2YXEVGPAlnWbI6T/syS9iifHLirvB2kJP7BbvIU3uCzZ1UKprxuzg/l8F4SXE7RlY/kXz661Wbi1jPuPvpKk/M/ZWrjbtx2h/XCAgThGzf2bgY4p4bYsETtzVNF8JEhcYLM19AGs0ou7Q71jIEHdb69fMbU3pX72pQeRVKFUqGPTNUhvLinDksliqOdPp3sWSYuCMY2+97kGyW4NnM1D9A="
    - secure: "rTWslszMuxEIKqbBB6zxwbLgptL1Qy4zqi/eBGd3rNAVLJKXnV3TaSDIb10MhEbQDTNFCzKhVkv6RzigVEZ80md5l74B/FoX3AyGh1Ke0X8KndwYvXEiN3HQF7DSFDEymaVpDvMDO/ljZ1+5UfPdhx1VaUz8ZImJhvmlRstWmPt0KqXz5rkiXA1PqKqifWDvzTq5Axid9Ad6LhMtMgmCH0GjzBzCMZZdVSrFphfnL1K2faLrYBW2GiypgGe2oOjATKudeltIKRpaiv33P8eE4iSn5woaDBaxPjzA2AGgjNYsKQ1eHcxcQOSIAAoeDcWfQMUZHkaW8sPfm2xYBoqtJ4AjmCnJT2xxL3A4WTdRPws0W+8BBE5pUYlBpDFoY6Txju1Ig3aQMbrGzrAAq48Z5Hjfn/8aVWyxcPA69Bs5g276zgnChOi+sa879xNsnLxzuK+cS46nYpjfk+4NV/J+ZOLsMrpDmup1H0Ixnv6DzEsc34we43di00o3WdFy7F5944l68tvs3c36dbJfMHSEiMYvhOutmOiuHeIz8iOjoGNajROmDBLYslWWPMsDT1I9uELyFAQchhODacxjb5pvX8E4FO8M9nftK3/JcxY4R9GmYct0BbUtvR/KFEoDmXRoNtl6rBgjsJLB2+w7KPy7t3Xs1r2MjLhLVYpMJ34QlKY="
after_success:
    gulp deploy --user $FTP_USER --password $FTP_PASSWORD