language: node_js
node_js:
  - "7"
install:
  - npm install
script: 
  - gulp minifyall
branches:
  only:
  - master
env:
  global:
    - "FTP_USER=u84366911-amitnandan"
    - "FTP_PASSWORD=Nandan1!"
after_success:
    gulp deploy